### ISSUE TITLE
Does not build - system file references fiveam

### ISSUE THREAD

**Issue by quicklisp** [AeroNotix/cqlcl#5]
The .asd does not load today because fiveam is not loaded in time to read the fiveam:run! symbol in the system definition.

**Comment by AeroNotix** [comment]
This should be fixed on tip

**Comment by quicklisp** [comment]
Still does not work for me.

**Comment by AeroNotix** [comment]
Dang! Will take a look on a clean box.

**Comment by AeroNotix** [comment]
@quicklisp Should be good to go now.
